# Generated by Django 5.0.4 on 2024-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_student_class_in_student_dob_student_name_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_in',
            field=models.CharField(default='High School', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
