# Generated by Django 5.0.4 on 2024-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_student_class_in_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_in',
            field=models.CharField(choices=[('High School', 'High School'), ('Intermediate', 'Intermediate')], default='High School', max_length=20),
        ),
    ]
