# Generated by Django 5.0.4 on 2024-04-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_alter_student_class_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_in',
            field=models.CharField(choices=[('High School', 'High School'), ('Intermediate', 'Intermediate')], default='High School', max_length=20),
        ),
    ]
